# Generated by Django 4.1.7 on 2023-03-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('S', 'Seller'), ('C', 'Customer')], default='S', max_length=1),
        ),
    ]
