# Generated by Django 4.1.7 on 2023-04-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0004_user_orders_user_shoppingcart_user_available_merch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
