# Generated by Django 4.1.7 on 2023-04-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0005_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
