# Generated by Django 4.1.7 on 2023-04-04 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0005_merchandise_is_approved_merchandise_poster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Orders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigMoney.shoppingcart'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
