# Generated by Django 4.1.7 on 2023-04-05 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0006_merchandise_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
