# Generated by Django 4.2 on 2023-04-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0006_remove_order_orders_remove_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
