# Generated by Django 4.2 on 2023-04-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0007_alter_merchandise_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to={'static/images/product_images'}),
        ),
    ]
