# Generated by Django 4.2 on 2023-04-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0008_alter_merchandise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to={'product_images'}),
        ),
    ]
