# Generated by Django 4.2 on 2023-04-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0010_rename_poster_shoppingcart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product_images'),
        ),
    ]
