# Generated by Django 4.2 on 2023-04-06 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0012_merchandise_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
