# Generated by Django 4.2 on 2023-04-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0015_cartitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='genres',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('books', 'Books'), ('movies', 'Movies'), ('computers', 'Computers'), ('food', 'Food'), ('cooking', 'Cooking'), ('outdoors', 'Outdoors')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
