# Generated by Django 4.2 on 2023-04-23 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigMoney', '0017_rename_genres_merchandise_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Order',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='bigMoney.cartitem'),
        ),
    ]
